services:
  dockerindocker:
    image: ghcr.io/rodrikv/vm-docker:master
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: 5G
        reservations:
          cpus: '0.25'
          memory: 256M
    privileged: true
    command: ["python3", "bot.py"]
    env_file:
        - .env
    ports:
      - ${open_ssh_port}:${open_ssh_port}
    volumes:
      - ./volumes:/home/volumes
