services:
  dockerindocker:
    image: ghcr.io/rodrikv/vm-docker:master
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: 5G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - TELEGRAM_API_TOKEN=
      - ENABLED_USERS=
      - ssh_pub_key=
      - ssh_port=
    ports:
      - $${ssh_port}:$${ssh_port}
    volumes:
      - ./volumes:/home/volumes
